experimenting with reducing remapping effects
Uniswap/permit2 pull request #160
Opened 2022-11-23 16:19 UTC by ewilz

we'll have some people importing solmate indirectly from node based projects. This is an experiment with configuring things as to not force them to have a remappings.txt file for their submodules. feel free to close though

2022-11-23 19:18 UTC, marktoda requested changes
Undo submodule updates, otherwise seems fine to me

2022-11-23 19:33 UTC, ewilz commented on remappings.txt
> +solmate/=lib/solmate/
had some trouble with this

2022-11-23 19:47 UTC, marktoda approved these changes

2022-11-23 19:47 UTC, marktoda commented on .gas-snapshot
> +MockPermit2Lib:testPermit2Code(address):(bool) (runs: 256, μ: 35465847065545473, ~: 2911)
waaaaat lol

2022-11-23 19:57 UTC, ewilz commented on .gas-snapshot
> +MockPermit2Lib:testPermit2Code(address):(bool) (runs: 256, μ: 35465847065545473, ~: 2911)
does this need to be investigated?

2022-12-06 15:44 UTC, merged

2023-12-06 05:21 UTC, seanmc9 commented
Am doing some work on [Juicebox Contracts v4](https://github.com/Bananapus/juice-contracts-v4/pull/54), which have this repo as a dependency, to get them fully using forge, but am running into an error where `PermitSignature.sol`'s `openzeppelin-contracts/contracts/utils/cryptography/draft-EIP712.sol` is attempting to read that file from the top level `lib/openzeppelin-contracts` folder instead of the `lib/permit2/lib/openzeppelin-contracts`.

The simplest answer to resolve this seems to be that the `remapping.txt` file in this repo should explicitly specify where this import should look, and so wanted to bring this up on the PR where y'all got rid of this, but I was curious if y'all have seen this issue at all and/or know of any alternatives I should try here to get the mapping to work correctly.

Thank you!

![image](https://github.com/Uniswap/permit2/assets/27874039/106ba3b3-02d8-4f09-bac3-c2a01d95149c)

2025-12-12 23:51 UTC, Tomiborges commented on remappings.txt
> +solmate/=lib/solmate/
Apaga tudo

2025-12-12 23:51 UTC, Tomiborges commented on remappings.txt
> +solmate/=lib/solmate/
Apaga tudo