allowance & sig transfer 721 support
Uniswap/permit2 pull request #171
Opened 2023-01-05 23:43 UTC by snreynolds

2023-01-11 13:19 UTC, hensha256 commented on src/ERC721/AllowanceTransfer_ERC721.sol
> +                allowed.tokenId = 0;
i think theres no rules around the use of ID 0 and the use of ID maxUint... and so i think we have to assume that those IDs can be valid too?
e.g. a user approves Permit2 for the NFT with ID maxUint - and the contract will assume theyre approving all NFTs?
Similarly I think there might be issues if a user holds the NFT with ID 0?

2023-01-11 13:33 UTC, hensha256 commented on src/ERC721/SignatureTransfer_ERC721.sol
> +                if (requestedTokenId != 0) {
token ID 0 can exist! So I dont think this line works

2023-01-11 13:39 UTC, hensha256 commented on src/ERC721/SignatureTransfer_ERC721.sol
> +                if (requestedTokenId != 0) {
okay came back with a concrete example
crypto punks has an ID 0!
Although punks arent ERC721, _wrapped_ cryptopunks are the 721 wrapper for punks and they use the same IDs. So there could easily be a wrapped punk with ID 0.

2023-01-11 13:45 UTC, hensha256 requested changes
I think the ID comments I've left sadly break this - the edge cases need to be thought through. Maybe you need to use a different field to signal whether an allowance/permit is active or not, because `0` doesnt work

2023-01-12 10:33 UTC, hensha256 commented on src/ERC721/AllowanceTransfer_ERC721.sol
>      mapping(address => mapping(address => mapping(address => PackedAllowance))) public allowance;
Given the 0 ID case needs to be fixed maybe a mapping like follows would solve both these at once
user address => token address => spender address => tokenID => allowance

or could pay tokenID with one of the addresses?

2023-01-12 21:43 UTC, snreynolds commented on src/ERC721/AllowanceTransfer_ERC721.sol
> +contract AllowanceTransfer_ERC721 is IAllowanceTransfer_ERC721, EIP712_ERC721 {
thats fair, can do prefix/suffix!

2023-01-12 21:46 UTC, snreynolds commented on src/ERC721/AllowanceTransfer_ERC721.sol
>      mapping(address => mapping(address => mapping(address => PackedAllowance))) public allowance;
makes sense. i think i'll add it as an index in the mapping, it would be nice to also allow operator approvals (no tokenId granularity) though which then would need to be a separate mapping. thoughts on this?

2023-01-13 01:44 UTC, snreynolds commented
Updated code with the following changes:
- the allowance mapping now indexes by `tokenId`. ty @hensha256 for pointing that out!
- included an operators mapping to still allow operator approvals which introduced two new functions: `setApprovalForAll` and another `permit` function.

One thing that I'd love some takes on:
I did NOT write a code path where passing in expiration as 0 (for the operator entrypoints) sets the expiration to block.timestamp even though that exists for the allowance mapping. I don't think we should enable this functionality bc I want to allow unsetting operators and the most intuitive way to do that is to pass in expiration as 0. Does this mean we should disable this functionality in the allowance mapping as well? This would be a departure from how ERC20 allowance mapping works.

2023-01-13 13:57 UTC, hensha256 commented on src/ERC721/AllowanceTransferERC721.sol
> +    mapping(address => mapping(address => mapping(uint256 => PackedAllowance))) public allowance;
mm this means you can only approve one spender right? I dont think I like that.
If another protocol integrates with Permit2 maybe a user would want to have 2 open approvals e.g. if they list their NFT for sale on 2 platforms?

2023-01-13 14:19 UTC, hensha256 commented on src/ERC721/AllowanceTransferERC721.sol
> +    mapping(address => mapping(address => mapping(uint256 => PackedAllowance))) public allowance;
hm i guess users can approve multiple spenders on the approve-all functionality at least

2023-01-13 17:20 UTC, snreynolds commented on src/ERC721/AllowanceTransferERC721.sol
> +    mapping(address => mapping(address => mapping(uint256 => PackedAllowance))) public allowance;
Yeah they can approve multiple spenders with approveAll.. also this is the erc721 standard https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC721/ERC721.sol#L36

2023-01-13 17:24 UTC, snreynolds commented on src/ERC721/AllowanceTransferERC721.sol
> +    mapping(address => mapping(address => mapping(uint256 => PackedAllowance))) public allowance;
also beneficial bc a new approval on the same tokenId is now a dirty store

2023-01-13 18:58 UTC, marktoda commented on src/ERC721/AllowanceTransferERC721.sol
> +        PackedOperatorAllowance storage operator = operators[msg.sender][permitAll.token][permitAll.spender];
Shouldn't this be `owner` instead of `msg.sender?

2023-01-13 18:58 UTC, marktoda commented on src/ERC721/AllowanceTransferERC721.sol
> +        }
nit: could remove a layer of nesting if you switch the ordering around:
```
if (allowed.spender == msg.sender) {
    allowed.spender = address(0)
} else if (operatorExpired) {
    revert InsufficientAllowance
}
```

2023-01-13 22:13 UTC, snreynolds commented on src/ERC721/AllowanceTransferERC721.sol
> +        PackedOperatorAllowance storage operator = operators[msg.sender][permitAll.token][permitAll.spender];
ah yes it should be

2023-01-17 16:14 UTC, hensha256 commented on src/ERC721/AllowanceTransferERC721.sol
> +    mapping(address => mapping(address => mapping(uint256 => PackedAllowance))) public allowance;
right yeah that makes sense. I didnt realise this was how it is in 721 - happy to just match that!

2023-01-17 16:18 UTC, hensha256 commented on src/ERC721/interfaces/IAllowanceTransferERC721.sol
> +    /// @dev Holds a nonce value to prevent replay protection.
_prevent replay protection_ feels like incorrect wording. _Provide_ replace protection?

2023-01-17 16:29 UTC, hensha256 commented on src/ERC721/AllowanceTransferERC721.sol
> +    function permit(address owner, PermitAll memory permitAll, bytes calldata signature) external {
Not sure if we'd want it, but have you thought about `PermitAllBatch`? Just because we normally support 2 versions of each type of permit: the singular and the batch versions. So we could do a batch "all" approval too.

But maybe overkill

2023-01-31 19:39 UTC, snreynolds commented on src/ERC721/AllowanceTransferERC721.sol
> +    function permit(address owner, PermitAll memory permitAll, bytes calldata signature) external {
mm yeah, i think i would opt to not include it since permitAll is a kind of batch, and maybe we even remove permitBatch in favor of permitAll

2023-02-06 17:47 UTC, marktoda approved these changes
lgtm!

2023-02-06 17:47 UTC, marktoda commented on src/ERC721/AllowanceTransferERC721.sol
> +    mapping(address => mapping(address => mapping(address => PackedOperatorAllowance))) public operators;
not a PR issue but we should upgrade to 0.8.18 so we can do `mapping(address user => mapping(address token => mapping(address spender => PackedOperatorAllowance)))` for better readability :D

2023-02-06 17:47 UTC, marktoda commented on src/ERC721/AllowanceTransferERC721.sol
> +            allowed.spender = address(0);
should we also clear expiry? No issues from keeping the stale expiry set? Shouldn't have any gas consequences since its just 1 sstore anyways

2023-02-06 18:21 UTC, snreynolds commented on src/ERC721/AllowanceTransferERC721.sol
> +    mapping(address => mapping(address => mapping(address => PackedOperatorAllowance))) public operators;
ah yes! huge readability improvement will do

2023-02-06 21:18 UTC, merged