downgrade interface pragmas
Uniswap/permit2 pull request #233
Opened 2023-09-07 00:01 UTC by lukasrosario

downgrading interface pragmas to ^0.8.0 for compatibility with projects that have permit2 as a dependency

2023-09-07 15:33 UTC, snreynolds requested changes
I think it would also be great to change them then for https://github.com/Uniswap/permit2/blob/main/src/interfaces/IDAIPermit.sol and https://github.com/Uniswap/permit2/blob/main/src/interfaces/IERC1271.sol just for some consistency

2023-09-07 15:37 UTC, lukasrosario commented
make sense, updated to be consistent 👍

2023-09-07 20:20 UTC, snreynolds approved these changes

2023-09-08 13:45 UTC, snreynolds commented
Merged here https://github.com/Uniswap/permit2/pull/235

2023-09-08 13:45 UTC, closed without merging